import { css } from '@emotion/css'

export const layout = {
  // TODO Container
  // Box Decoration
  'decoration-slice': css({ boxDecorationBreak: 'slice' }),
  'decoration-clone': css({ boxDecorationBreak: 'clone' }),
  // Box Sizing
  'box-border': css({ boxSizing: 'border-box' }),
  'box-content': css({ boxSizing: 'content-box' }),
  // Display
  block: css({ display: 'block' }),
  'inline-block': css({ display: 'inline-block' }),
  inline: css({ display: 'inline' }),
  flex: css({ display: 'flex' }),
  'inline-flex': css({ display: 'inline-flex' }),
  table: css({ display: 'table' }),
  'inline-table': css({ display: 'inline-table' }),
  'table-caption': css({ display: 'table-caption' }),
  'table-cell': css({ display: 'table-cell' }),
  'table-column': css({ display: 'table-column' }),
  'table-column-group': css({ display: 'table-column-group' }),
  'table-footer-group': css({ display: 'table-footer-group' }),
  'table-header-group': css({ display: 'table-header-group' }),
  'table-row-group': css({ display: 'table-row-group' }),
  'table-row': css({ display: 'table-row' }),
  'flow-root': css({ display: 'flow-root' }),
  grid: css({ display: 'grid' }),
  'inline-grid': css({ display: 'inline-grid' }),
  contents: css({ display: 'contents' }),
  'list-item': css({ display: 'list-item' }),
  hidden: css({ display: 'none' }),
  // Floats
  'float-right': css({ float: 'right' }),
  'float-left': css({ float: 'left' }),
  'float-none': css({ float: 'none' }),
  // Clear
  'clear-left': css({ clear: 'left' }),
  'clear-right': css({ clear: 'right' }),
  'clear-both': css({ clear: 'both' }),
  'clear-none': css({ clear: 'none' }),
  // Isolation
  isolate: css({ isolation: 'isolate' }),
  'isolation-auto': css({ isolation: 'auto' }),
  // Object Fit
  'object-contain': css({ objectFit: 'contain' }),
  'object-cover': css({ objectFit: 'cover' }),
  'object-fill': css({ objectFit: 'fill' }),
  'object-none': css({ objectFit: 'none' }),
  'object-scale-down': css({ objectFit: 'scale-down' }),
  // Object Position
  'object-bottom': css({ objectPosition: 'bottom' }),
  'object-center': css({ objectPosition: 'center' }),
  'object-left': css({ objectPosition: 'left' }),
  'object-left-bottom': css({ objectPosition: 'left bottom' }),
  'object-left-top': css({ objectPosition: 'left top' }),
  'object-right': css({ objectPosition: 'right' }),
  'object-right-bottom': css({ objectPosition: 'right bottom' }),
  'object-right-top': css({ objectPosition: 'right top' }),
  'object-top': css({ objectPosition: 'top' }),
  // Overflow
  'overflow-auto': css({ overflow: 'auto' }),
  'overflow-hidden': css({ overflow: 'hidden' }),
  'overflow-visible': css({ overflow: 'visible' }),
  'overflow-scroll': css({ overflow: 'scroll' }),
  'overflow-x-auto': css({ overflowX: 'auto' }),
  'overflow-y-auto': css({ overflowY: 'auto' }),
  'overflow-x-hidden': css({ overflowX: 'hidden' }),
  'overflow-y-hidden': css({ overflowY: 'hidden' }),
  'overflow-x-visible': css({ overflowX: 'visible' }),
  'overflow-y-visible': css({ overflowY: 'visible' }),
  'overflow-x-scroll': css({ overflowX: 'scroll' }),
  'overflow-y-scroll': css({ overflowY: 'scroll' }),
  // Overscroll Behavior
  'overscroll-auto': css({ overscrollBehavior: 'auto' }),
  'overscroll-contain': css({ overscrollBehavior: 'contain' }),
  'overscroll-none': css({ overscrollBehavior: 'none' }),
  'overscroll-y-auto': css({ overscrollBehaviorY: 'auto' }),
  'overscroll-y-contain': css({ overscrollBehaviorY: 'contain' }),
  'overscroll-y-none': css({ overscrollBehaviorY: 'none' }),
  'overscroll-x-auto': css({ overscrollBehaviorX: 'auto' }),
  'overscroll-x-contain': css({ overscrollBehaviorX: 'contain' }),
  'overscroll-x-none': css({ overscrollBehaviorX: 'none' }),
  // Position
  static: css({ position: 'static' }),
  fixed: css({ position: 'fixed' }),
  absolute: css({ position: 'absolute' }),
  relative: css({ position: 'relative' }),
  sticky: css({ position: 'sticky' }),
  // TODO Top / Right / Bottom / Left
  visible: css({ visibility: 'visible' }),
  invisible: css({ visibility: 'hidden' }),
  // Z-Index
  'z-0': css({ 'z-index': '0' }),
  'z-10': css({ 'z-index': '10' }),
  'z-20': css({ 'z-index': '20' }),
  'z-30': css({ 'z-index': '30' }),
  'z-40': css({ 'z-index': '40' }),
  'z-50': css({ 'z-index': '50' }),
  'z-auto': css({ 'z-index': 'auto' }),
}
